#!/bin/sh

PATH=/sbin:/usr/sbin:/bin:/usr/bin
export PATH

set -eu

if [ ! -d /etc/postfix-prestash ]; then
	postmulti -e init
	postmulti -e create -I postfix-prestash
	postconf -c /etc/postfix-prestash -e \
	    'authorized_submit_users = root' \
	    'mydestination =' \
	    'alias_maps =' \
	    'alias_database =' \
	    'local_recipient_maps =' \
	    'local_transport = error:5.1.1 Mailbox invalid' \
	    'default_transport = prestash:$myhostname' \
	    'export_environment = TZ MAIL_CONFIG LANG'

	cat >> /etc/postfix-prestash/master.cf <<'EOF'
prestash unix  -       n       n       -       -       pipe
  flags=hu user=krb5notify argv=/usr/bin/prestash-notify ${domain}
EOF
	postmulti -e enable -i prestash
fi

if ! postmulti -i prestash -p status >/dev/null 2>&1; then
	postmulti -i prestash -p start
fi
